### ISSUE TITLE
getcatchWgt not working

### ISSUE THREAD

**Issue by pdolder** [ices-tools-prod/icesDatras#36]
Hi,

getCatchWgt throws an error for duplicate row names. For example, 

dat <- getCatchWgt(survey = "NS-IBTS", years = 2018, quarters = c(1), aphia = 126436)

This seems to be a recent problem, as it was not happening earlier in the year.

**Comment by colinpmillar** [comment]
Thanks Paul - will check it out - it may be an R 4.0 issue, or something with the web service data being returned

**Comment by pdolder** [comment]
That could well be it, I have moved to R 4.0.  I just tried to test on R
3.6 but got a timed out from the web service...

**Comment by pdolder** [comment]
It's not the R version, got the same error with 3.6.2

**Comment by colinpmillar** [comment]
I think you have cracked it - the issue is the function does not use the full key, I have fixed in the development branch - I think - would you mind checking your code against it @pdolder?

the changes are here: https://github.com/ices-tools-prod/icesDatras/commit/dcb76dc52a3bc40dedf8b3c91383e8a35334bec3
in the getCatchWgt.R file

**Comment by pdolder** [comment]
That was it, seems to work fine now.

Cheers

**Comment by colinpmillar** [comment]
thanks! I will publish to cran soon - I have an issue with the icesVocab package to sort out first...
