### ISSUE TITLE
Function names

### ISSUE THREAD

**Issue by arnima-github** [ices-tools-prod/icesDatras#6]
I think the function names could be simplified. An improved naming scheme could also help people to better understand how the functions are related to each other. Here's one idea.
1. The four functions to import datasets keep their current names: getHHdata, getHLdata, getCAdata, getDATRAS.
2. The four functions to list available data start with the prefix "list":
   getSurveyList -> listSurveys
   getSurveyYearList -> listYears
   getSurveyYearQuarterList -> listQuarters
   getDatrasDataOverview -> listEverything

I volunteer to make this change, or something in this direction, if you guys agree. The current naming scheme has all functions starting with get*something, and some function names are rather long.

**Comment by arnima-github** [comment]
Most of the functions are named after the corresponding web service API functions. So it's debatable which is more practical, to use the API names for consistency or provide the R user with function names that make most sense at that level. So there's at least three options regarding function names in icesDatras:

a) Use the current names.
b) Use something like the naming scheme outlined above.
c) Use the corresponding API function names, but a different name for non-API functions like getDatrasDataOverview(). That function could be called inventoryDatras(), for example.

No strong opinion here, just thoughts from a beginning user who has a keen interest in easy and efficient user interfaces.

**Comment by einarhjorleifsson** [comment]
i think you should take a totally different approach. in Rstudio (which is what i think is for now the prevalent gui) when one types
```
get
```
one gets a long list of "suggestion". i.e. `get` is used everywhere. if you are striving to consistency within a package i rather suggest going the way hadley did with the `stringr` package. most user accessible function start with  `str_`
in your case you may think of `datras_` as a prefix. or some shorter acronym (`dtrs_`??). the get-part is redundant (because all the function in the package are essentially get).

within that you may want to think about using the acronyms we have used in our tribal quarters at skulagata 4 when returning assessment results dataframes:

> rby - results by year
> rbya - results by year and age
> rba - results by age

of course here it would not be r (results) but d (data)?

the above is just a thought which has to, if you go with it, to be adapted to the datras data. but by all means get rid of this "HH", "HL", "CA" stuff. nobody but the brussel clan understands that. the datras data is bigger than that.

> "What's in a name? That which we call a rose
> By any other name would smell as sweet."
> Shakespeare

einar

**Comment by colinpmillar** [comment]
Just sticking with the old names now ;)  one of the ideas with the ices web services packages when we started out was to name the R functions exactly the same as the web services themselves.  this is what is done for icesSAG, icesDatras and icesVocab, next time we will probably deviate a bit from the web service names to make the functions a bit more readable.
