### ISSUE TITLE
Memory leaks in XML parsing

### ISSUE THREAD

**Issue by colinpmillar** [ices-tools-prod/icesDatras#8]
There seems to be serious memory leaks when parsing the XML files, particularly when using the new "peek and pop" method.  

A solution could be to move to the xml2 package.

**Comment by slarge** [comment]
In your crystal ball, do you foresee a need (or desire) to compose XML for submission to DATRAS? As far as I can tell, the inability to translate data.frame - XML is one limitation to xml2. Otherwise, I adopted the proposed approach in the old version, here: https://github.com/ices-tools-dev/rICES/blob/master/R/getDATRAS.R .

**Comment by colinpmillar** [comment]
Fixed by treating xml as text and manually processing
